model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VAE
  params:
    monitor: "val/rec_loss"
    emb_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 1.0e-06
        disc_weight: 0.5
    ddconfig:
      z_channels: 4
      resolution: 64
      in_ch: 3
      out_ch: 3
      ch: 32
      ch_mult: [1,1,2,2,4]
      num_res_blocks: 2
      attn_resolutions: [8]
data:
  target: main.StreetSatDataModule
  params:
    batch_size: 8
    train:
      target: data.datasets.StreetSatTrain
    val:
      target: data.datasets.StreetSatVal
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2